name       : frotz
version    : '2.51'
release    : 3
source     :
    - https://gitlab.com/DavidGriffith/frotz/-/archive/2.51/frotz-2.51.tar.bz2 : 7e488140791259a1a8c9e16a0c467ca69b694b918c28ffe3d83c654bcb253cca
homepage   : https://davidgriffith.gitlab.io/frotz/
license    : GPL-2.0-or-later
component  : games.emulator
summary    : Z-Machine interpreter for playing interactive fiction games
description: |
    Z-Machine interpreter for playing interactive fiction games.
builddeps  :
    - pkgconfig(ao)
    - pkgconfig(libmodplug)
    - pkgconfig(ncursesw)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
build      : |
    %make
install    : |
    %make_install PREFIX=$installdir/usr
